GET http://localhost:3003/api/blogs
###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    //"title": "aadfadsf",
    "author": "AntonAnton",
    //"url": "blog.fi/anton/blog",
    "likes": 3
}

###

DELETE http://localhost:3003/api/blogs/263050f5c0cd920ae8116591f

###

GET  http://localhost:3003/api/blogs/6322009c29f8ed2de170ee47
###
GET  http://localhost:3003/info
